### ISSUE TITLE
Nested Loop access to _eachLoop.list

### ISSUE THREAD

**Issue by rhythmicdevil** [coolony/kiwi#10]
Hi,
I am having a problem with the each loops.

 If I remove the inner loop then the conditional that evaluates _eachLoop.last works correctly in that it identifies the final iteration.

 If I put it back in then the conditional seems to identify each of the inner loops iterations as the final iteration.

My goal is to iterate the following structure outputting headings and a list of values for each heading.

```
data : {
    "heading1" : [ 'item1', 'item2', 'item3' ],
    "heading2" : [ 'item1', 'item2', 'item3' ],
}
```

Where am I going wrong?

```
<div class="row show-grid">
    {{each data}}
        {{as namespace}}${$index}{{/as}}

        {{if _eachLoop.first }}
        <div class="span3">
        {{/if}}

        <h3>${$index}</h3>

        {{each $value}}
        <div><a href="/alias_tests/alias/${namespace}${$value}">${$value}</a></div>
        {{/each}}

        {{if _eachLoop.last }}
        </div>
        {{/if}}
    {{/each}}
</div>
```

Thanks for the help.

**Comment by pierreis** [comment]
Thanks for the report. I'm looking at this.

**Comment by pierreis** [comment]
Okay, figured out what the issue was.
A variable declaration was in the wrong place, which caused issues with nested loops.

I'll commit a patch shortly (probably tomorrow morning) with some additional tests.

**Comment by rhythmicdevil** [comment]
Fantastic. Thanks for work man I really appreciate it.

**Comment by pierreis** [comment]
This issue has been fixed in the development version.
Please just note that, even though `_eachLoop` still works, this is deprecated and should be replaced with `$each`. This is to make the variable naming scheme in Kiwi more consistent.

As a bonus, I'll probably add soon `$each.parentIndex` and `$each.parentValue`.

**Comment by rhythmicdevil** [comment]
Great thanks.
