### ISSUE TITLE
Custom Filter

### ISSUE THREAD

**Issue by rhythmicdevil** [coolony/kiwi#11]
Hi,
I am trying to create a custom filter to format JSON. I have tried to create the filter two ways and both fail with the same error. I tried the method shown in the docs:

This is just a test function and really does nothing.

```
Kiwi.tools.createFilter('json_format', function(str){
    console.log(str);
return str.toUpperCase(); 
});
```

I also tried adding a new function to /libs/filters/base.js

```
exports.json_filter = function(str) {
     console.log(str);
    return str.toUpperCase(); 
};
```

I then use it in the template like this: 

```
<div class="test interactive" title="Click to run the Alias">${test.test|json_filter}</div>
```

The error output is the same in both cases.

```
/home/swright/code/noschema_cp/node_modules/kiwi/lib/tags/print.js:163
                     filter[1] = filter[1].replace('"', '\"');
                                       ^
TypeError: Cannot read property '1' of null
    at mapOne (/home/swright/code/noschema_cp/node_modules/kiwi/lib/tags/print.js:163:40)
    at Array.map (native)
    at parseFilters (/home/swright/code/noschema_cp/node_modules/kiwi/lib/tags/print.js:161:21)
    at Object.compile (/home/swright/code/noschema_cp/node_modules/kiwi/lib/tags/print.js:104:31)
    at LeafToken.compile (/home/swright/code/noschema_cp/node_modules/kiwi/lib/token.js:297:31)
    at Timer.compileOne (/home/swright/code/noschema_cp/node_modules/kiwi/lib/utils.js:205:11)
    at Timer.processOne [as _callback]   (/home/swright/code/noschema_cp/node_modules/kiwi/node_modules/frame/lib/async_foreach.js:43:8)
    at Timer.<anonymous> (timers.js:172:14)
```

**Comment by pierreis** [comment]
The parser expects filter names to only contain letters (case doesn't matter).
I'll add the underscore tomorrow, plus a more helpful error message.

Thanks.

**Comment by rhythmicdevil** [comment]
Aha. Thank you. I will use camelcase for the naming.

**Comment by pierreis** [comment]
BTW, I don't know whether you noticed, but a `json` filter is already included in Kiwi.

**Comment by rhythmicdevil** [comment]
I did actually but I want to do a JSON formatter. I have JSON objects that I need to show a user in a readable format. Right now I am using your JSON filter and then wrapping the output in pre tags. Its sufficient for the moment but I would like to add highlighting as well.

**Comment by pierreis** [comment]
This issue has been fixed in the development version.
Additionally,  an helpful error message will be thrown by `createFilter` or `createSimpleTag` when defining filters or tags with invalid names.

**Comment by rhythmicdevil** [comment]
Excellent, thank you.
