### ISSUE TITLE
Add vars to {{include}} tag

### ISSUE THREAD

**Issue by moshest** [coolony/kiwi#12]
Ability to set a locals vars for inner template file.
For example:

{{each rows}}
   {{include item=$value type="top"}}
{{/each}}

Inspired by Smarty engine for php.

**Comment by pierreis** [comment]
Great idea. Thanks.
However, the syntax you are proposing is not really consistent with Kiwi's syntax, or with any JS-like syntax.

I will probably instead add an additional `context` parameter, which takes a JS object injected in the included file context.

`{{include "menu.kiwi" myContextObject}}`

**Comment by pierreis** [comment]
This has been pushed to the repository.
`{{include}}` and `{{extend}}` tags now support passing a context object as second arg.

**Comment by moshest** [comment]
Nice!
Thanks.

**Comment by panosru** [comment]
This is actually what [macros](http://jinja.pocoo.org/docs/templates/#macros) are about :)
