### ISSUE TITLE
Prepend/Append work opposite 

### ISSUE THREAD

**Issue by panosru** [coolony/kiwi#13]
Hi, `prepend` and `append` work in opposite direction from which they supposed to work.

For instance: 

**main.kiwi**

``` twig
{{block foobar}}foo{{/block}}
```

**child1.kiwi**

``` twig
{{block foobar append}} bar{{/block}}
```

**child2.kiwi**

``` twig
{{block foobar prepend}}bar {{/block}}
```

**child1.kiwi** supposed to return `foo bar` but it returns `barfoo` similar issue happens with **child2.kiwi**

**Comment by pierreis** [comment]
I can't believe this has passed the tests... Thanks.
Fixed in 732966795bf86b795d3b2807bc1c496b66c36c30.
