### ISSUE TITLE
Unknown filter `raw`

### ISSUE THREAD

**Issue by panosru** [coolony/kiwi#16]
From the [docs](https://github.com/coolony/kiwi#escaping-by-default) `raw` filter is mentioned but when I try to use it I get `Error: Rendering error: Unknown filter raw.` from what I see in the source of Kiwi under `lib/filters/base.js` `raw` filter is not present.

**Comment by panosru** [comment]
Ah I was trying this: `{{= foobar|raw }}` instead of `${foobar|raw}`

So filters are not working with `{{= }}` ?

**Comment by pierreis** [comment]
It _is_ working with `{{= }}` (actually, a preprocessor translates all `${}` internally before parsing).
Just that it does not (as of today) trim the filter names.

`{{= foo|raw}}` will work, `{{= foo|raw }}` won't.

I will add support for this.

**Comment by panosru** [comment]
ah I see, tricky one :) 

Thanks!
