### ISSUE TITLE
Support for Macros?

### ISSUE THREAD

**Issue by panosru** [coolony/kiwi#3]
Hi, would it be possible to support [macros](http://jinja.pocoo.org/docs/templates/#macros) ?

**Comment by pierreis** [comment]
Hello,

Macros actually are on my ToDo list for a future release. Takes time to implement.

Thanks =)

**Comment by panosru** [comment]
Thanks for letting me know :)

**Comment by panosru** [comment]
@unicyclon Is it possible to publish the todo list for Kiwi so public could know what to expect? :)

Thanks!

**Comment by pierreis** [comment]
Done.

Sorry for the late answer, I was pretty busy these days. Better now :)

**Comment by panosru** [comment]
@pierresforge Hello again! Until macros are implemented I was wondering if I could use `{{include}}` somehow as a workaround.

I have this template:

**message.kiwi**

``` html
{{if !type}}{{as type}}success{{/as}}{{/if}}
{{if !closable}}{{as closable}}true{{/as}}{{/if}}
{{if !size}}{{as size}}grid_12{{/as}}{{/if}}
<ul class="message ${type} ${size}">
  <li>${content|raw}</li>
  {{if closable}}
  <li class="close-bt"></li>
  {{/if}}
</ul>
```

and I call it like this:
`{{include message context}}` where context is an object that contains `content` and optionally may contain `type`, `closable`, `size`. Would be great if I could call it like this though `{{include message { content : 'Hello World!', type : 'info'} }}`

**Comment by pierreis** [comment]
Hello!

Unfortunately, as of today, the parser won't handle tags like `{{include message { content : 'Hello World!', type ; 'info'} }}`.
But, this may be your lucky day. I am working on a tiny patch to address this issue.

Stay tuned!

**Comment by panosru** [comment]
@pierresforge Thanks mate!

Strange thing that I notice now is that `{{include "../__macro/message.kw.html" context}}` is not working for me as I though it should... :/

In my controller I have:

``` js
res.render('index', {
      context : {
        content : 'Hello world!'
      }
    });
```

and when I do `${context.content}` I get `Hello World!`, seems that the object is not passed properly. The error I got is this:

```
timers.js:103
            if (!process.listeners('uncaughtException').length) throw e;

                                      ^
SyntaxError: Unexpected identifier
    at Object.Function (unknown source)
    at onCompiled (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/compiler.js:70:16)
    at onCompiled (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/token.js:182:5)
    at exports.compileTokens (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/utils.js:236:5)
    at done (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/utils.js:215:5)
    at handleProcessedCallback (/usr/local/lib/node_modules/protos/node_modules/kiwi/node_modules/frame/lib/async_foreach.js:37:7)
    at onCompiled (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/utils.js:208:7)
    at onCompiled (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/token.js:249:5)
    at blockTag.compile (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/tags/block.js:96:3)
    at onIntermediateCompiled (/usr/local/lib/node_modules/protos/node_modules/kiwi/lib/token.js:241:5)
```

I registered the engine to work both with `.kiwi` and `.kw.html` extensions

**Comment by pierreis** [comment]
Hummm.
Strange thing. I'm looking at this issue right now.

**Comment by pierreis** [comment]
I just fixed a first issue related to your report with error handling. Cf. cad9394011b1c41fea53b999082465ef6ea264af.

And I unfortunately can't reproduce your issue.
Here is my test case:

**main.kiwi**

``` html
Variable: ${message}
{{include "child" context}}
{{include "child2" context}}
```

**child.kiwi**

``` html
Included message: ${message}
```

**child2.kiwi**

``` html
Included message (legacy method): ${context.message}
```

**Code**

``` javascript
res.render('foo', {
  message: 'Should be on the first line!',
  context: {
    message: 'Should be on the second (and on the third)...'
  }
});
```

**Result**

```
Variable: Should be on the first line!
Included message: Should be on the second (and on the third)...
Included message (legacy method): Should be on the second (and on the third)...
```

So, everything seems to work just as expected. I can't reproduce your issue.
Are you sure you're using the right Kiwi version? This particular feature has yet to be pushed to the NPM registry.

If yes, can you send me your complete failing code so I can reproduce it?

**Comment by panosru** [comment]
@pierresforge indeed I didn't had the latest version but now I saw another issue.

I have a **main.kiwi** file and a **child .kiwi** file, **child.kiwi** extends **main.kiwi**, `{{include "../__macro/message.kw.html" context}}` works outside of `{{block}}` tag but when is inside `{{block}}` tag then the page is load for ever, obviously the script continuously loop itself.

**Comment by pierreis** [comment]
Indeed, I can reproduce that one.
Looking at it.

**Comment by pierreis** [comment]
Well. This one is worse than it seems.
I'm currently writing a fix for this.

However, this kind of problems won't happen anymore with the new parser and compiler I'm currently writing, which will easily handle this kind of things, plus a lot more, and allow faster rendering of templates a the cost of a slightly longer compilation time. Expected anytime this week.
