### ISSUE TITLE
FEATURE REQUEST: support for {{parent}} tag

### ISSUE THREAD

**Issue by hypno2000** [coolony/kiwi#4]
for example:

// foo.kiwi
{{block greeting}}Hello{{/block}}

// Template
{{extend "foo"}}
{{block greeting}}Hi, {{parent}} World{{/block}}

// Code
new Template(tpl).render({}, callback);

// Result
Hi, Hello World

**Comment by pierreis** [comment]
Good idea. Thanks.
This would only require minor changes to be implemented. I'll have a look at it anytime soon.

**Comment by pierreis** [comment]
Just added experimental support for this.
Wrote basic test for it. I'll do more careful testing when I have some more time.

Feel free to further comment on this issue, if needed.
