### ISSUE TITLE
Example Problem

### ISSUE THREAD

**Issue by rhythmicdevil** [coolony/kiwi#8]
Hi,
Engine looks great so far. In your examples you have this which actually fails because 'name' is undefined:

<!DOCTYPE html>
<html>
  <head>
    <title>${title}</title>
  </head>
  <body>
    <p>
      {{if name}}
        Hello, ${name|capitalize}!
      {{else}}
        Hello, dear unknown!
      {{/if}}
    </p>
  </body>
</html>

Should be something like this:

<!DOCTYPE html>
<html>
  <head>
    <title>${title}</title>
  </head>
  <body>
    <p>
      {{if typeof(name) != 'undefined'}}
        Hello, ${name|capitalize}!
      {{else}}
        Hello, dear unknown!
      {{/if}}
    </p>
  </body>
</html>

**Comment by pierreis** [comment]
This is just meant to be a general syntax example, not really a template working out of the box.
I'm currently updating the doc, I'll add a line about this shortly.

Thanks for noticing.
