### ISSUE TITLE
Rendering an array of objects in {{each}}

### ISSUE THREAD

**Issue by mavdi** [coolony/kiwi#9]
Hi,

I was wondering if it is possible to feed an array of objects to {{each}} tag. and then read the properties of the objects

for example

```
var item1 = {title : "Hi", content : "Hola" };
var item2 = {title : "Hello", content : "Buenos" };

response.render("index", posts = [item1, item2]);
```

in kiwi

```
{{each posts}}
<p>title is ${value.title} and content is ${value.content}</p>
{{/each}}
```

**Comment by mavdi** [comment]
My mistake... Apologies, this works perfectly fine!

**Comment by pierreis** [comment]
Yeah. Of course you can.

Your approach is good. You just made a mistake on the variable name:

```
{{each posts}}
<p>title is ${$value.title} and content is ${$value.content}</p>
{{/each}}
```

You can change the default names (`$value` and `$index`) with the `{{each(value, index) array}}` syntax. I'm currently documenting this.
